apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: image-registry.openshift-image-registry.svc:5000/spring-apps-cicd/spring-app
  newTag: latest
namespace: spring-apps-dev
