apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
- spring-apps-dev-ns.yaml
- spring-apps-dev-rb.yaml

images:
- name: quay.io/kskels/spring-app
  newTag: 'latest'

replicas:
- name: spring-app
  count: 1

namespace: spring-apps-dev
