apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-app
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - image: quay.io/kskels/spring-app
          imagePullPolicy: Always
          name: spring-app
          ports:
            - containerPort: 8080
              protocol: TCP

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP

          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
