apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-app
  name: spring-app
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-app
