apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
spec:
  storageClassName: "ocs-storagecluster-ceph-rbd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
