apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
- spring-apps-demo-ns.yaml

images:
- name: quay.io/kskels/spring-app
  newTag: '1.0'

replicas:
- name: spring-app
  count: 8

namespace: spring-apps-demo
