apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: spring-app
  name: spring-app
  namespace: spring-apps-cicd
spec:
  output:
    to:
      kind: DockerImage
      name: docker.apps.ocp4.kskels.com/demos/spring-app:latest
    pushSecret:
      name: "nexus-docker-registry"
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/ubi8/openjdk-11
    type: Source
