apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
- spring-apps-staging-ns.yaml
- spring-apps-staging-rb.yaml

images:
- name: quay.io/kskels/spring-app
  newTag: staging
namespace: spring-apps-staging
