apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-app
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-apps-prod
  project: default
  source:
    path: deploy/kustomize/overlays/prod
    repoURL: https://github.com/kskels/spring-app.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
